# Generated by Django 4.2.3 on 2023-08-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appetizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="chicken/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tag", models.ManyToManyField(blank=True, to="ingredients.tag")),
            ],
        ),
    ]
