# Generated by Django 4.2.3 on 2023-08-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chicken", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chicken",
            old_name="details_image",
            new_name="image",
        ),
    ]
