# Generated by Django 4.2.3 on 2023-08-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0003_alter_basemodel_name"),
        ("chicken", "0002_rename_details_image_chicken_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chicken",
            name="tag",
        ),
        migrations.AddField(
            model_name="chicken",
            name="tag",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ingredients.tag",
            ),
        ),
    ]
