# Generated by Django 4.2.3 on 2023-08-02 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cheese",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ingredients.basemodel",
                    ),
                ),
            ],
            bases=("ingredients.basemodel",),
        ),
        migrations.CreateModel(
            name="Meat",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ingredients.basemodel",
                    ),
                ),
            ],
            bases=("ingredients.basemodel",),
        ),
        migrations.CreateModel(
            name="Sauce",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ingredients.basemodel",
                    ),
                ),
            ],
            bases=("ingredients.basemodel",),
        ),
        migrations.CreateModel(
            name="Spice",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ingredients.basemodel",
                    ),
                ),
            ],
            bases=("ingredients.basemodel",),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ingredients.basemodel",
                    ),
                ),
                ("tag_image", models.ImageField(upload_to="tags/")),
            ],
            bases=("ingredients.basemodel",),
        ),
        migrations.CreateModel(
            name="Vegetable",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ingredients.basemodel",
                    ),
                ),
            ],
            bases=("ingredients.basemodel",),
        ),
    ]
