# Generated by Django 4.2.3 on 2023-08-01 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ingredients.basemodel",
                    ),
                ),
                ("tag_image", models.ImageField(upload_to="tags/")),
            ],
            bases=("ingredients.basemodel",),
        ),
    ]
