# Generated by Django 4.2.3 on 2023-08-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0002_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basemodel",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
