# Generated by Django 4.2.3 on 2023-08-01 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0003_alter_basemodel_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="tag_image",
        ),
    ]
