# Generated by Django 4.2.3 on 2023-08-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0004_remove_tag_tag_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="tag_image",
            field=models.ImageField(default=1, upload_to="tags/"),
            preserve_default=False,
        ),
    ]
