# Generated by Django 4.2.3 on 2023-08-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DoughType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Средна", "Средна"),
                            ("Голяма", "Голяма"),
                            ("Джъмбо", "Джъмбо"),
                        ],
                        max_length=100,
                    ),
                ),
                ("picture", models.ImageField(upload_to="dough/")),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
