# Generated by Django 4.2.3 on 2023-08-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dough_types", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doughtype",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doughtype",
            name="picture",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doughtype",
            name="price",
            field=models.DecimalField(decimal_places=2, default=2, max_digits=6),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="DoughSubType",
        ),
    ]
