# Generated by Django 4.2.3 on 2023-08-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dough_types", "0002_doughtype_description_doughtype_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doughtype",
            name="type",
            field=models.CharField(
                choices=[
                    ("Средна", "Средна"),
                    ("Голяма", "Голяма"),
                    ("Джъмбо", "Джъмбо"),
                ],
                max_length=100,
            ),
        ),
    ]
