# Generated by Django 4.2.3 on 2023-08-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dough_types", "0003_alter_doughtype_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doughtype",
            name="picture",
            field=models.ImageField(upload_to="dough/"),
        ),
    ]
