# Generated by Django 4.2.3 on 2023-08-02 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dough_types", "0001_initial"),
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("front_description", models.TextField()),
                ("front_image", models.ImageField(upload_to="pizzas/front/")),
                ("details_description", models.TextField()),
                ("details_image", models.ImageField(upload_to="pizzas/details/")),
                ("cheese", models.ManyToManyField(blank=True, to="ingredients.cheese")),
                (
                    "dough_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dough_types.doughtype",
                    ),
                ),
                ("meats", models.ManyToManyField(blank=True, to="ingredients.meat")),
                ("sauce", models.ManyToManyField(blank=True, to="ingredients.sauce")),
                ("spices", models.ManyToManyField(blank=True, to="ingredients.spice")),
                ("tags", models.ManyToManyField(blank=True, to="ingredients.tag")),
                (
                    "vegetables",
                    models.ManyToManyField(blank=True, to="ingredients.vegetable"),
                ),
            ],
        ),
    ]
