# Generated by Django 4.2.3 on 2023-08-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pizza", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pizza",
            name="price",
        ),
    ]
