# Generated by Django 4.2.3 on 2023-08-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0002_tag"),
        ("pizza", "0002_remove_pizza_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pizza",
            old_name="description",
            new_name="details_description",
        ),
        migrations.RemoveField(
            model_name="pizza",
            name="image",
        ),
        migrations.AddField(
            model_name="pizza",
            name="details_image",
            field=models.ImageField(default=2, upload_to="pizzas/details/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pizza",
            name="front_description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pizza",
            name="front_image",
            field=models.ImageField(default=1, upload_to="pizzas/front/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pizza",
            name="tag",
            field=models.ManyToManyField(blank=True, to="ingredients.tag"),
        ),
    ]
