# Generated by Django 4.2.3 on 2023-08-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0003_alter_basemodel_name"),
        ("pizza", "0004_remove_pizza_tag_pizza_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pizza",
            name="tag",
        ),
        migrations.AddField(
            model_name="pizza",
            name="tag",
            field=models.ManyToManyField(blank=True, to="ingredients.tag"),
        ),
    ]
